version: '3.8'

services:
  mongo:
    image: mongo:8.0.0
    restart: always
    container_name: mongo
    volumes:
      - $HOME/uzrnem/database/mongo/data:/data/db
    ports:
      - 27017:27017
    networks: 
      - mongo-database  
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongoui
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongo:${DATABASE_PORT}/
  
    ports:
      - 8081:8081
    networks: 
      - mongo-database
networks:  
  mongo-database:
    driver: bridge
